name: 工作流程

on:
  schedule:
    - cron: '0 15 * * 3'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v7

      - name: 删除文件
        run: rm -f data/{clash.yaml,singbox.json,subscribes.txt,v2ray.txt,valid-domains.txt}

      - name: 设置环境
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: 安装依赖
        run: pip install --upgrade pip pyYAML tqdm geoip2

      - name: 运行脚本
        run: python -u subscribe/collect.py --skip

      - name: 提交更改
        run: |
          git config --local user.name "nnby"
          git config --local user.email "wus5b38@outlook.com"
          git add data/*
          git commit -m "Update: $(date '+%Y-%m-%d %H:%M:%S')"
          git push

      - name: 删除工作流程
        uses: Mattraks/delete-workflow-runs@main
        continue-on-error: true
        with:
          retain_days: "0"
          keep_minimum_runs: "1"
